[package]
name = "example-std"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
embedded-hal = "0.2.7"
defmt = "0.3.2"
defmt-serial = { version = "*", path = "../" }
nb = "1.0.0"
